### ISSUE TITLE
Character Substitution usage failed

### ISSUE THREAD

**Issue by canyeweishang** [AtomCrafty/UniversalInjectorFramework#2]
The game tested was まほ×ろば -Witches spiritual home-
After use, it will be displayed as shown in the figure below
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/103740149/da7be948-5178-49f7-a2c3-e337f98d16ad)
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/103740149/c48cf935-708f-404a-ba94-762c723bb9b6)
I would like to ask if you have any solution

**Comment by AtomCrafty** [comment]
The log shows that none of the four function UIF tried to hook are imported by the exe itself. That could either mean that the game uses a different Windows API to render text, or that the text rendering code is not contained in the exe but in a dll file.

Could you upload the exe and all dlls for me to check out?

**Comment by canyeweishang** [comment]
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/103740149/b1c67904-5465-43a0-ab32-c72f39c6294d)
All the files of the game are shown in the picture above, there is no dll, and the game exe has been uploaded
[mahoXroba.zip](https://github.com/AtomCrafty/UniversalInjectorFramework/files/13383427/mahoXroba.zip)

**Comment by AtomCrafty** [comment]
Hmm, that is unusual. The game uses `GetGlyphOutlineW` to render glyphs, but for some reason the injector did not find the import. Specifically `DetourEnumerateImportsEx` fails to enumerate the exe's import address table at all because the entries seem to have been tampered with. The `OriginalFirstThunk` field of each import descriptor is `NULL`, which shouldn't ordinarily be the case.
The segments have nonstandard names as well (`._____`, `seg002`, `seg003`, etc.), which leads me to believe that either this was compiled with a strange compiler or there was some sort of tamper protection applied after the fact.

Unfortunately I'm not sure how to work around the issue, since I have to rely on Detours to enumerate the IAT properly.

**Comment by canyeweishang** [comment]
Thanks for the answer, I'll try to use something else to fix this
