### ISSUE TITLE
Adding a function

### ISSUE THREAD

**Issue by Cosetto** [AtomCrafty/UniversalInjectorFramework#3]
Hello there, the Window Manager function works very great, but I wonder is it possible to add a function like it for text in exe?
Like this [link](https://github.com/Cosetto/RiaLibrary/blob/1852389207af01d362b84a279d7953eb6dae4581/lib/RxHook/src/Mem.cpp#L14-L18)
You have RVA (Relative Virtual Address), and you can change the text at that address.
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/81801486/aac14929-75ec-495a-9f07-bd6f102ce887)

But the problem is I want to use it in your proxies because it converts Ansi to UTF16 for special characters.

**Comment by AtomCrafty** [comment]
If you're implementing a custom UIF feature, you can use `patch_memory` from `utils.h`, that works essentially the same as your `SysMemWrite` function. But UIF actually already comes with a built-in feature that can do this without any code modifications.
But apparently I forgot to write documentation for it in the readme, so here is how to use it.

Just add the following to your `uif_config.json`:
```json
{
  "memory_patcher": {
    "enable": true,
    "patches": {
      "myTargetModule.dll+0016BDB4h": "54 6F 61 6E 20 6D 61 6E 20 68 69 6E 68 20 28 4F 29",
      "myTargetModule.dll+00172CB4h": "43 68 75 79 82 BA 6E 20 74 82 BC 6E 68 20 63 75 82 B1 69 0A 63 82 C1 6E 67 20 74 72 82 B5 6E 20 54 72 82 9F 69 20 83 83 82 A5 74 2E"
    }
  }
}
```

If your `image_base` refers to the main executable, you can omit the `myTargetModule.dll+` part of the addresses. Also note that the address offset must end in `h` or `H` to signal that it's a hexadecimal number, otherwise it's parsed as decimal. The patch string must be separated by a single space and if any of them are less than 16, they need a leading zero.

**Comment by Cosetto** [comment]
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/81801486/fdf636ab-9dc4-433b-8f60-5442c71b216f)
Hm, I tried with utf8 hex, but it turned out like this.

Aside from that, what is the format we use to patch with string?

**Comment by AtomCrafty** [comment]
Well of course the new string has to use the same encoding as the original. The code processing these strings doesn't magically get changed to support UTF-8 if it expects to find Shift-JIS strings.

So the next step is to determine which API ultimately consumes the string. That would probably be `InsertMenu` or a related function, since it ends up in a popup menu. The UIF text processing features (`tunnel_decoder` and `character_substitution`) currently don't support those menu APIs, but they should be fairly straightforward to add hooks for. Assuming the program uses codepage 932 / Shift-JIS, you can encode the string with arc's tunnel encoding. Then we'd just need to implement the appropriate hook for the tunnel decoder.

I was planning a rework of the entire text processing subsystem in the near-ish future, so I can look into adding support for the relevant APIs. I can't make any promises regarding times though, so if you want to add the hooks yourself, check out the existing hooks in `tunnel_decoder.cpp`.

**Comment by Cosetto** [comment]
Ah, I see.
Thank you for your answer. Guess I'll wait for that day to come.

**Comment by AtomCrafty** [comment]
@Cosetto could you share the executable so I can check which function needs to be hooked?

**Comment by Cosetto** [comment]
@AtomCrafty Here 
[eden_en.zip](https://github.com/AtomCrafty/UniversalInjectorFramework/files/13766400/eden_en.zip)

**Comment by AtomCrafty** [comment]
Which proxy dll are you using?

**Comment by Cosetto** [comment]
I'm using winmm

**Comment by AtomCrafty** [comment]
[winmm.zip](https://github.com/AtomCrafty/UniversalInjectorFramework/files/13766784/winmm.zip)
Please check whether this works.

**Comment by Cosetto** [comment]
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/81801486/6f817fb2-0118-4f62-8dcf-2a482accb22f)
It became "Toan man minh"
"à" -> "a"
"ì" -> "i"

**Comment by AtomCrafty** [comment]
Could you copy/paste the console output for me to check?

**Comment by Cosetto** [comment]
> DllMain: attach
> InstallDelayedAttachHook: start
> InstallDelayedAttachHook: no target module specified
> InstallDelayedAttachHook: transaction
> InstallDelayedAttachHook: end
> Attach: run
> Attach: unhook
> injector::attach: enabled
> DllMain: detach

**Comment by AtomCrafty** [comment]
Not the log file, the output shown in the console window that should open with the program. Should look something like this.
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/4553050/d22a5f66-dea1-4f48-be27-74dda9f87071)

**Comment by Cosetto** [comment]
Universal Injector Framework, created by AtomCrafty, 2021
Loaded configuration:
{
    "allocate_console": true,
    "text_processor": {
        "conversion_codepage": 65001,
        "enable": true,
        "enabled_apis": [
            "AppendMenuA"
        ],
        "rules": [
            {
                "apis": [
                    "AppendMenuA"
                ],
                "match": "Full screen (&O)",
                "replacement": "Toàn màn hình",
                "type": "replace_full_string"
            }
        ]
    }
}
[injector] ======================================================
[injector] Injecting into module eden_en.exe at address 00400000
[injector] Loading original library from C:\Windows\system32\winmm.dll
[text_processor] Hooking import AppendMenuA in eden_en.exe at 005492E4 --> 6C831680
[injector] Initialization complete
[injector] ======================================================

**Comment by AtomCrafty** [comment]
[winmm.zip](https://github.com/AtomCrafty/UniversalInjectorFramework/files/13766871/winmm.zip)
I added some debug output, maybe that will shed some light on what's going on here.

Btw if you use Discord, you can add me there (@atomcrafty). That might be easier for this kind of troubleshooting.

**Comment by AtomCrafty** [comment]
[winmm.zip](https://github.com/AtomCrafty/UniversalInjectorFramework/files/13767037/winmm.zip)
I think I found the issue. Try this one.

**Comment by Cosetto** [comment]
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/81801486/70d0bbbd-ec03-487d-9a0f-4dedd7b710fc)
Oh nice, it work!!

**Comment by AtomCrafty** [comment]
Sweet!

**Comment by Cosetto** [comment]
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/81801486/79958909-458a-4a4f-99fc-b5efbc506a50)
So, is the correct way to continue?

**Comment by AtomCrafty** [comment]
Every rule definition needs to be in its own `{}` block.
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/4553050/9c804f0d-cc8b-4839-b91e-831b8af589a5)

**Comment by Cosetto** [comment]
Thanks!

**Comment by Cosetto** [comment]
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/81801486/7b553818-eccf-4b72-bcdc-22fff7064a74)
Weird, this time the "window_manager" didn't work

**Comment by AtomCrafty** [comment]
`text_processor` replaces all of the old text modification features, including `window_manager`.
Use this configuration instead:
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/4553050/871f9029-089b-4ba0-a22e-31c186f16be2)

**Comment by Cosetto** [comment]
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/81801486/cf0d3a7e-ea16-4904-a3f0-8b8379487794)
@AtomCrafty Any idea for Unicode string?

**Comment by AtomCrafty** [comment]
Add `MessageBoxW` to the `enabled_apis` list and use this rule:
```
{
	"type": "replace_full_string",
	"apis": ["MessageBoxW"],
	"match": "Are you sure you want to exit?",
	"replacement": "Translation here"
}
```

**Comment by Cosetto** [comment]
Lol, it seems like each Unicode string has bytes to indicate the length before it. So that was why it didn't catch full string.
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/81801486/0d04d61b-9631-4cec-b140-55bcba3d36f6)

**Comment by AtomCrafty** [comment]
How the data is represented in memory shouldn't matter at all, since UIF doesn't touch them there. This data is manipulated by the application and the end result is ultimately passed to one of the `MessageBox__` functions. It only matters what is passed to that function since that is where UIF does the replacement. But looking at the executable it appears that it uses `MessageBoxA` instead of `MessageBoxW`, do try replacing both instances in your config.

**Comment by Cosetto** [comment]
Oh, it works now. Thanks again pal!

**Comment by Cosetto** [comment]
Sorry for bothering you again, but it looks like there are few more string which don't use MessageBoxA. Do you know how to determine which api they use?
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/81801486/bed2c275-b4a2-4927-8026-4edcb086e8b4)
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/81801486/e4867600-b167-4afd-aab8-c2fbba3e2645)

**Comment by AtomCrafty** [comment]
The program probably never sets the text explicitly, but just loads it from the dialog template. So there is no API UIF could intercept to change the string. Looks like you're already using Resource Hacker, so the easiest option would be to just edit the dialog template right there.

**Comment by Cosetto** [comment]
Aight'
